version: "3.8"
services:
  database:
    restart: always
    image: bitnami/postgresql:10.20.0
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=$POSTGRES_USER
      - POSTGRESQL_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRESQL_DATABASE=$POSTGRES_DB
    volumes:
      - ./db/data/postgres:/bitnami/postgresql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  backend:
    depends_on:
      - database
      - sesion_api
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=database
      - PORT=$BACKEND_PORT
    volumes:
      - ./backend/index.js:/home/node/index.js
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
  frontend:
    depends_on:
      - database
      - backend
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_PORT=$BACKEND_PORT
      - REACT_APP_BACKEND_HOST=backend
      - PORT=$FRONTEND_PORT
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
  nginx:
    depends_on:
      - database
      - backend
      - frontend
    restart: always
    image: nginx:1.20.2-alpine
    ports:
      - $NGINX_PORT:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  redis:
    restart: always
    image: bitnami/redis:6.0.16
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis/data:/data
  sesion_api:
    depends_on:
      - redis
    restart: always
    build:
      context: ./sesion_api
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_SECRET=$REDIS_SECRET
      - SESION_API_PORT=$SESION_API_PORT
    volumes:
      - ./sesion_api/index.js:/home/node/index.js
    ports:
      - "$SESION_API_PORT:$SESION_API_PORT"